"""
core/squad_value_model.py
-------------------------
Squad market-value Elo adjustment for international fixtures.

Uses Transfermarkt approximate squad valuations (€M) to derive a
relative-strength signal that complements the historical Elo ratings.

Formula
-------
    adj = clip(30 * log2(home_value / away_value), -150, +150)

Calibration:
  ratio = 1.0  →  adj =   0  (equal squads, no effect)
  ratio = 2.0  →  adj = +30  (~2.4% win prob boost)
  ratio = 10.0 →  adj = +100 (~8% win prob boost)
  ratio = 0.1  →  adj = -100 (penalty when massively outclassed)

The adjustment is added to the home team's effective Elo rating before
the win-probability calculation.  Values are sourced from
`data/models/squad_values.json` (generated by scripts/scrape_squad_values.py).
"""

from __future__ import annotations

import json
import math
from pathlib import Path

SQUAD_VALUES_PATH = Path("data/models/squad_values.json")

_CACHE: dict | None = None


def load_squad_values() -> dict[str, float]:
    """Load squad values from JSON, caching the result in memory.

    Returns an empty dict if the file does not exist, rather than raising.
    """
    global _CACHE
    if _CACHE is None:
        if SQUAD_VALUES_PATH.exists():
            with open(SQUAD_VALUES_PATH, encoding="utf-8") as f:
                _CACHE = json.load(f)
        else:
            _CACHE = {}
    return _CACHE


def squad_elo_adjustment(home_team: str, away_team: str) -> float:
    """Return the Elo adjustment to add to the home team's effective Elo.

    Formula: ``clip(30 * log2(ratio), -150, +150)``
    where ``ratio = home_squad_value / away_squad_value``.

    Calibration
    -----------
    * ratio = 10  →  +100 Elo pts  →  ~8% win probability boost (neutral)
    * ratio =  1  →    0 Elo pts   →  no change
    * ratio = 0.1 →  -100 Elo pts  →  ~8% penalty when outclassed

    Returns 0.0 if either team is absent from the squad-values data or if
    the away team's value is zero (avoids division by zero).
    """
    vals = load_squad_values()
    home_val = vals.get(home_team)
    away_val = vals.get(away_team)

    if not home_val or not away_val or away_val <= 0:
        return 0.0

    ratio = home_val / away_val
    adj = 30.0 * math.log2(ratio)
    return max(-150.0, min(150.0, adj))


def get_squad_values(home_team: str, away_team: str) -> dict:
    """Return a metadata dict with raw squad values and ratio for diagnostics.

    Keys
    ----
    home_squad_value_m : float | None
        Home team total squad value in €M.
    away_squad_value_m : float | None
        Away team total squad value in €M.
    squad_value_ratio : float | None
        home / away ratio; None if either team is missing.
    squad_elo_adj : float
        The Elo adjustment already computed (convenience).
    """
    vals = load_squad_values()
    home_val = vals.get(home_team)
    away_val = vals.get(away_team)

    ratio: float | None = None
    if home_val is not None and away_val and away_val > 0:
        ratio = home_val / away_val

    return {
        "home_squad_value_m": home_val,
        "away_squad_value_m": away_val,
        "squad_value_ratio": ratio,
        "squad_elo_adj": squad_elo_adjustment(home_team, away_team),
    }
